name: usbtop
version: '0.1'
summary: See an estimated instantaneous bandwidth on USB buses and devices.
description: |
  Monitor your usb traffic on the bus using the usbmon kernel module.
  (see https://www.kernel.org/doc/Documentation/usb/usbmon.txt for more
  details)
  .
  Find the source for this snap at https://github.com/ogra1/usbtop
  And the upstream tree for usbtop at https://github.com/aguinet/usbtop
  .
  This snap uses a large amount of snap interfaces make sure to connect
  all of them after installing the snap.

grade: stable
confinement: devmode

apps:
  usbtop:
    command: usbtop
    plugs: 
      - account-control
      - bluetooth-control
      - firewall-control
      - hardware-observe
      - kernel-module-control
      - network
      - network-bind
      - network-control
      - network-observe
      - netlink-connector
      - netlink-audit
      - raw-usb
  lsusb:
    command: lsusb
    plugs: 
      - account-control
      - bluetooth-control
      - firewall-control
      - hardware-observe
      - network
      - network-bind
      - network-control
      - network-observe
      - netlink-connector
      - netlink-audit
      - raw-usb

parts:
  usbtop:
    plugin: cmake
    source: https://github.com/aguinet/usbtop.git
    source-tag: release-0.1
    configflags: 
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - libboost-dev
      - libpcap-dev
      - libboost-thread-dev
      - libboost-system-dev
    stage-packages:
      - kmod
      - libpcap0.8
      - usbutils
    install: |
      mv $SNAPCRAFT_PART_INSTALL/sbin/usbtop $SNAPCRAFT_PART_INSTALL/sbin/usbtop.real
      cp ../src/LICENSE $SNAPCRAFT_PART_INSTALL/
  script:
    plugin: nil
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/sbin
      cp usbtop $SNAPCRAFT_PART_INSTALL/sbin/
    after: [ usbtop ]
